### ISSUE TITLE
Hello 

### ISSUE THREAD

**Issue by teraoo** [blastingpenisinthesky/beer-brooch#1]
ERROR tera-proxy-game: [dispatch] write: failed to generate C_USE_ITEM<3>
error: [protocol] write - C_USE_ITEM<3>: error writing "dbid" (type: uint64)
data: null
reason: Cannot read property 'low' of null

(Caali-Proxy)

**Comment by blastingpenisinthesky** [comment]
https://github.com/hackerman-caali/tera-data/tree/master/protocol

Download C_USE_ITEM 3 and paste it in teraproxy/node_modules/tera-data/protocol
